const cardsDetail1 = [
  {
    name: 'Bar in Motion',
    description: 'The Bar in Motion is a project done in the first Microverse module milestone. I created the project as a reference to the halloween holiday function organized by the Bar in Motion Communuty. The project was able to communicate the fun events that were organized for the day and also worked as a marketing strategy for the company by displaying their previous events',
    canopy: 'FIGMA',
    back: 'Landing Page',
    year: '2021',
    image: 'images/bar1.png',
    tech1: 'html',
    tech2: 'css',
    tech3: 'javascript',
    closBtn: 'images/close.png',
    buttn1: 'See live',
    buttn2: 'See Source',
    counterOne: 'images/Counter.jpg',
    counterTwo: 'images/Counter.jpg',
    live: 'images/live.jpg',
    gity: 'images/gitty.jpg',
    liveLink: 'https://mosams.github.io/Module-One-Capstone-Project/',
    liveGit: 'https://github.com/Mosams/Module-One-Capstone-Project.git',
  },

  {
    name: 'Space Travelers',
    description: `This is a web application that facilitates booking rockets and join selected space missions. 
    It is built for a company that offers both commercial and scientific space travel services. The application also
     works with real live data from the SpaceX API.`,
    canopy: 'CANOPY',
    back: 'Back End Dev',
    year: '2015',
    image: 'images/spacetravelerspic2.png',
    tech1: 'html',
    tech2: 'css',
    tech3: 'javascript',
    closBtn: 'images/close.jpg',
    buttn1: 'See live',
    buttn2: 'See Source',
    counterOne: 'images/Counter.jpg',
    counterTwo: 'images/Counter.jpg',
    live: 'images/live.jpg',
    gity: 'images/gitty.jpg',
    liveLink: 'https://space-traveler-s-hub.netlify.app/',
    liveGit: 'https://github.com/Mosams/space_travellers.git',
  },
  {
    name: 'Yu-Gi-Oh App',
    description: `This application displays a number of cards based where a user can click on each of the card to like their favourite card. 
    The app also has a comment section link which when clicked on leads the user to a comment section popup 
    containing more detailed information about the card. In this section, the user is also able to leave a comment based on the experience and
     inquires they might have. Both pages have counters to display the number of comments and items on the screen.

    Yu-Gi-Oh is a Japanese manga series about trading card gaming written and illustrated by Kazuki Takahashi. It was serialized in Shueisha's Weekly Shōnen Jump magazine between September 1996 and March 2004. The plot follows the story of a boy named Yugi Mutou, who solves the ancient Millennium Puzzle. Yugi awakens a gambling alter-ego or spirit within his body that solves his conflicts using various games.`,
    canopy: 'Front End',
    back: 'Back End',
    year: '2021',
    image: 'images/Yu-Gi-Oh.png',
    tech1: 'html/css',
    tech2: 'WEBPACK',
    tech3: 'javascript',
    closBtn: 'images/close.jpg',
    buttn1: 'See live',
    buttn2: 'See Source',
    counterOne: 'images/Counter.jpg',
    counterTwo: 'images/Counter.jpg',
    live: 'images/live.jpg',
    gity: 'images/gitty.jpg',
    liveLink: 'https://mosams.github.io/Module-One-Capstone-Project/',
    liveGit: 'https://github.com/Mosams/Module-One-Capstone-Project.git',
  },
  {
    name: 'Multi-Post Stories',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent',
    canopy: 'CANOPY',
    back: 'Back End Dev',
    year: '2015',
    image: 'images/card4.jpg',
    tech1: 'html',
    tech2: 'css',
    tech3: 'javascript',
    closBtn: 'images/close.jpg',
    buttn1: 'See live',
    buttn2: 'See Source',
    counterOne: 'images/Counter.jpg',
    counterTwo: 'images/Counter.jpg',
    live: 'images/live.jpg',
    gity: 'images/gitty.jpg',
    liveLink: 'https://mosams.github.io/Module-One-Capstone-Project/',
    liveGit: 'https://github.com/Mosams/Module-One-Capstone-Project.git',
  },
];

export default cardsDetail1;